[package]
name = "countdown"
version = "0.1.0"
authors = ["James Pharaoh <james@pharaoh.uk>"]
edition = "2018"

[lib]
name = "countdown"

[[bin]]
name = "countdown-cli"
path = "src/bin/cli.rs"

[dependencies]
rand = "0.6"

[profile.release]
lto = true

