[package]

	name = "countdown"
	version = "0.1.0"
	authors = ["James Pharaoh <james@pharaoh.uk>"]
	edition = "2021"

[lib]

	name = "countdown"

[[bin]]

	name = "countdown-cli"
	path = "src/bin/cli.rs"

[dependencies]

	rand = "*"

[profile.release]

	lto = true

